version: '3.4'

services:
  hackathon.content.api:
    image: ${DOCKER_REGISTRY-}hackathoncontentapi
    build:
      context: .
      dockerfile: Hackathon.Content.Api/Dockerfile
    depends_on:
       - "gremlin-server"

  gremlin-server:
     image: tinkerpop/gremlin-server
     ports:
       - "8182:8182"
     volumes: 
        - ./data/:/data/

  rabbitmq-server:
     image: rabbitmq:3-management-alpine
     ports:
      - "15672:15672"
      - "5672:5672"